"use client"

import React, { createContext, useContext, useState } from 'react'

interface Translations {
  [key: string]: string | Translations | any
}

interface LanguageContextType {
  locale: string
  setLocale: (locale: string) => void
  t: (key: string) => string | any
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Простые переводы
const translations: Record<string, Translations> = {
  ru: {
    header: {
      title: "МЕТРИКА",
      subtitle: "Агентство недвижимости"
    },
    home: {
      welcome: "Добро пожаловать в портал агентства недвижимости МЕТРИКА. Здесь вы найдете все необходимое для работы с недвижимостью.",
      realEstateObjects: "Объекты недвижимости",
      realEstateObjectsDesc: "Просматривайте и управляйте объектами недвижимости",
      interactiveMap: "Интерактивная карта",
      interactiveMapDesc: "Изучайте объекты на карте города",
      knowledgeBase: "База знаний",
      knowledgeBaseDesc: "Получайте доступ к экспертной информации",
      useMenu: "Используйте меню слева для навигации по порталу"
    },
    menu: {
      home: "Главная",
      objects: "Объекты",
      map: "Карта",
      about: "О компании",
      contacts: "Контакты",
      blog: "Блог",
      profile: "Личный кабинет",
      myObjects: "Мои объекты",
      academy: "Академия",
      knowledgeBase: "База знаний",
      tasks: "Менеджер задач",
      admin: "Админ панель",
      login: "Войти",
      logout: "Выйти"
    },
    objects: {
      title: "Объекты недвижимости",
      filters: "Фильтры",
      propertyType: "Тип недвижимости",
      apartments: "Квартиры",
      houses: "Дома с участками",
      commercial: "Коммерческая",
      land: "Земельные участки",
      nonCapital: "Некапитальные",
      shares: "Доли",
      price: "Цена",
      priceFrom: "От",
      priceTo: "До",
      area: "Площадь (м²)",
      areaFrom: "От",
      areaTo: "До",
      district: "Район",
      allDistricts: "Все районы",
      central: "Центральный",
      northern: "Северный",
      southern: "Южный",
      eastern: "Восточный",
      western: "Западный",
      applyFilters: "Применить фильтры",
      reset: "Сбросить",
      found: "Найдено",
      objects: "объектов",
      sortBy: "По дате добавления",
      sortByPriceAsc: "По цене (возрастание)",
      sortByPriceDesc: "По цене (убывание)",
      sortByArea: "По площади",
      photo: "Фото",
      previous: "Назад",
      next: "Далее"
    },
    map: {
      title: "Интерактивная карта",
      description: "Изучайте объекты недвижимости на карте города",
      searchPlaceholder: "Поиск по адресу...",
      filters: "Фильтры",
      showAllObjects: "Показать все объекты",
      hideObjects: "Скрыть объекты",
      zoomIn: "Приблизить",
      zoomOut: "Отдалить",
      fullscreen: "Полный экран",
      legend: "Легенда",
      apartments: "Квартиры",
      houses: "Дома",
      commercial: "Коммерческая",
      land: "Земельные участки"
    },
    about: {
      title: "О компании",
      description: "МЕТРИКА - ведущее агентство недвижимости",
      mission: "Наша миссия",
      missionText: "Предоставлять качественные услуги в сфере недвижимости",
      values: "Наши ценности",
      valuesList: [
        "Профессионализм",
        "Честность",
        "Надежность",
        "Индивидуальный подход"
      ],
      team: "Наша команда",
      teamText: "Опытные специалисты с многолетним стажем",
      experience: "Опыт работы",
      experienceText: "Более 10 лет на рынке недвижимости"
    },
    contacts: {
      title: "Контакты",
      description: "Свяжитесь с нами любым удобным способом",
      phone: "Телефон",
      email: "Email",
      address: "Адрес",
      workingHours: "Режим работы",
      workingHoursText: "Пн-Пт: 9:00-18:00, Сб-Вс: 10:00-16:00",
      office: "Офис",
      officeAddress: "г. Москва, ул. Тверская, д. 15",
      support: "Техническая поддержка",
      supportEmail: "support@metrika.ru"
    }
  },
  en: {
    header: {
      title: "METRIKA",
      subtitle: "Real Estate Agency"
    },
    home: {
      welcome: "Welcome to the METRIKA real estate agency portal. Here you will find everything you need for working with real estate.",
      realEstateObjects: "Real Estate Objects",
      realEstateObjectsDesc: "View and manage real estate objects",
      interactiveMap: "Interactive Map",
      interactiveMapDesc: "Explore objects on the city map",
      knowledgeBase: "Knowledge Base",
      knowledgeBaseDesc: "Get access to expert information",
      useMenu: "Use the menu on the left to navigate the portal"
    },
    menu: {
      home: "Home",
      objects: "Objects",
      map: "Map",
      about: "About Us",
      contacts: "Contacts",
      blog: "Blog",
      profile: "Profile",
      myObjects: "My Objects",
      academy: "Academy",
      knowledgeBase: "Knowledge Base",
      tasks: "Task Manager",
      admin: "Admin Panel",
      login: "Login",
      logout: "Logout"
    },
    objects: {
      title: "Real Estate Objects",
      filters: "Filters",
      propertyType: "Property Type",
      apartments: "Apartments",
      houses: "Houses with Land",
      commercial: "Commercial",
      land: "Land Plots",
      nonCapital: "Non-Capital",
      shares: "Shares",
      price: "Price",
      priceFrom: "From",
      priceTo: "To",
      area: "Area (m²)",
      areaFrom: "From",
      areaTo: "To",
      district: "District",
      allDistricts: "All Districts",
      central: "Central",
      northern: "Northern",
      southern: "Southern",
      eastern: "Eastern",
      western: "Western",
      applyFilters: "Apply Filters",
      reset: "Reset",
      found: "Found",
      objects: "objects",
      sortBy: "By Date Added",
      sortByPriceAsc: "By Price (Ascending)",
      sortByPriceDesc: "By Price (Descending)",
      sortByArea: "By Area",
      photo: "Photo",
      previous: "Previous",
      next: "Next"
    },
    map: {
      title: "Interactive Map",
      description: "Explore real estate objects on the city map",
      searchPlaceholder: "Search by address...",
      filters: "Filters",
      showAllObjects: "Show All Objects",
      hideObjects: "Hide Objects",
      zoomIn: "Zoom In",
      zoomOut: "Zoom Out",
      fullscreen: "Fullscreen",
      legend: "Legend",
      apartments: "Apartments",
      houses: "Houses",
      commercial: "Commercial",
      land: "Land Plots"
    },
    about: {
      title: "About Us",
      description: "METRIKA - leading real estate agency",
      mission: "Our Mission",
      missionText: "To provide quality services in real estate",
      values: "Our Values",
      valuesList: [
        "Professionalism",
        "Honesty",
        "Reliability",
        "Individual Approach"
      ],
      team: "Our Team",
      teamText: "Experienced specialists with many years of experience",
      experience: "Work Experience",
      experienceText: "More than 10 years in real estate market"
    },
    contacts: {
      title: "Contacts",
      description: "Contact us in any convenient way",
      phone: "Phone",
      email: "Email",
      address: "Address",
      workingHours: "Working Hours",
      workingHoursText: "Mon-Fri: 9:00-18:00, Sat-Sun: 10:00-16:00",
      office: "Office",
      officeAddress: "Moscow, Tverskaya St., 15",
      support: "Technical Support",
      supportEmail: "support@metrika.ru"
    }
  },
  th: {
    header: {
      title: "เมตริกา",
      subtitle: "บริษัทอสังหาริมทรัพย์"
    },
    home: {
      welcome: "ยินดีต้อนรับสู่พอร์ทัลบริษัทอสังหาริมทรัพย์เมตริกา ที่นี่คุณจะพบทุกสิ่งที่จำเป็นสำหรับการทำงานกับอสังหาริมทรัพย์",
      realEstateObjects: "อสังหาริมทรัพย์",
      realEstateObjectsDesc: "ดูและจัดการอสังหาริมทรัพย์",
      interactiveMap: "แผนที่แบบโต้ตอบ",
      interactiveMapDesc: "สำรวจอสังหาริมทรัพย์บนแผนที่เมือง",
      knowledgeBase: "ฐานความรู้",
      knowledgeBaseDesc: "เข้าถึงข้อมูลผู้เชี่ยวชาญ",
      useMenu: "ใช้เมนูทางซ้ายเพื่อนำทางในพอร์ทัล"
    },
    menu: {
      home: "หน้าแรก",
      objects: "อสังหาริมทรัพย์",
      map: "แผนที่",
      about: "เกี่ยวกับเรา",
      contacts: "ติดต่อ",
      blog: "บล็อก",
      profile: "โปรไฟล์",
      myObjects: "อสังหาริมทรัพย์ของฉัน",
      academy: "สถาบัน",
      knowledgeBase: "ฐานความรู้",
      tasks: "จัดการงาน",
      admin: "แผงควบคุมผู้ดูแล",
      login: "เข้าสู่ระบบ",
      logout: "ออกจากระบบ"
    },
    objects: {
      title: "อสังหาริมทรัพย์",
      filters: "ตัวกรอง",
      propertyType: "ประเภทอสังหาริมทรัพย์",
      apartments: "อพาร์ตเมนต์",
      houses: "บ้านพร้อมที่ดิน",
      commercial: "เชิงพาณิชย์",
      land: "ที่ดิน",
      nonCapital: "ไม่ใช่ทุน",
      shares: "หุ้น",
      price: "ราคา",
      priceFrom: "จาก",
      priceTo: "ถึง",
      area: "พื้นที่ (ตร.ม.)",
      areaFrom: "จาก",
      areaTo: "ถึง",
      district: "เขต",
      allDistricts: "ทุกเขต",
      central: "กลาง",
      northern: "เหนือ",
      southern: "ใต้",
      eastern: "ตะวันออก",
      western: "ตะวันตก",
      applyFilters: "ใช้ตัวกรอง",
      reset: "รีเซ็ต",
      found: "พบ",
      objects: "รายการ",
      sortBy: "ตามวันที่เพิ่ม",
      sortByPriceAsc: "ตามราคา (น้อยไปมาก)",
      sortByPriceDesc: "ตามราคา (มากไปน้อย)",
      sortByArea: "ตามพื้นที่",
      photo: "รูปภาพ",
      previous: "ก่อนหน้า",
      next: "ถัดไป"
    },
    map: {
      title: "แผนที่แบบโต้ตอบ",
      description: "สำรวจอสังหาริมทรัพย์บนแผนที่เมือง",
      searchPlaceholder: "ค้นหาตามที่อยู่...",
      filters: "ตัวกรอง",
      showAllObjects: "แสดงอสังหาริมทรัพย์ทั้งหมด",
      hideObjects: "ซ่อนอสังหาริมทรัพย์",
      zoomIn: "ขยาย",
      zoomOut: "ย่อ",
      fullscreen: "เต็มหน้าจอ",
      legend: "คำอธิบาย",
      apartments: "อพาร์ตเมนต์",
      houses: "บ้าน",
      commercial: "เชิงพาณิชย์",
      land: "ที่ดิน"
    },
    about: {
      title: "เกี่ยวกับเรา",
      description: "เมตริกา - บริษัทอสังหาริมทรัพย์ชั้นนำ",
      mission: "พันธกิจของเรา",
      missionText: "ให้บริการคุณภาพในด้านอสังหาริมทรัพย์",
      values: "ค่านิยมของเรา",
      valuesList: [
        "ความเป็นมืออาชีพ",
        "ความซื่อสัตย์",
        "ความน่าเชื่อถือ",
        "แนวทางเฉพาะบุคคล"
      ],
      team: "ทีมของเรา",
      teamText: "ผู้เชี่ยวชาญที่มีประสบการณ์หลายปี",
      experience: "ประสบการณ์การทำงาน",
      experienceText: "มากกว่า 10 ปีในตลาดอสังหาริมทรัพย์"
    },
    contacts: {
      title: "ติดต่อ",
      description: "ติดต่อเราด้วยวิธีที่สะดวก",
      phone: "โทรศัพท์",
      email: "อีเมล",
      address: "ที่อยู่",
      workingHours: "เวลาทำการ",
      workingHoursText: "จ-ศ: 9:00-18:00, ส-อา: 10:00-16:00",
      office: "สำนักงาน",
      officeAddress: "กรุงมอสโก ถนน Tverskaya 15",
      support: "ฝ่ายสนับสนุนเทคนิค",
      supportEmail: "support@metrika.ru"
    }
  },
  hy: {
    header: {
      title: "ՄԵՏՐԻԿԱ",
      subtitle: "Անշարժ գույքի գործակալություն"
    },
    home: {
      welcome: "Բարի գալուստ ՄԵՏՐԻԿԱ անշարժ գույքի գործակալության պորտալ: Այստեղ դուք կգտնեք անշարժ գույքի հետ աշխատելու համար անհրաժեշտ ամեն ինչ:",
      realEstateObjects: "Անշարժ գույքի օբյեկտներ",
      realEstateObjectsDesc: "Դիտեք և կառավարեք անշարժ գույքի օբյեկտները",
      interactiveMap: "Ինտերակտիվ քարտեզ",
      interactiveMapDesc: "Ուսումնասիրեք օբյեկտները քաղաքի քարտեզի վրա",
      knowledgeBase: "Գիտելիքների բազա",
      knowledgeBaseDesc: "Մուտք ստացեք փորձագիտական տեղեկատվությանը",
      useMenu: "Օգտագործեք ձախ մենյուն պորտալում նավարկելու համար"
    },
    menu: {
      home: "Գլխավոր",
      objects: "Օբյեկտներ",
      map: "Քարտեզ",
      about: "Մեր մասին",
      contacts: "Կապ",
      blog: "Բլոգ",
      profile: "Պրոֆիլ",
      myObjects: "Իմ օբյեկտները",
      academy: "Ակադեմիա",
      knowledgeBase: "Գիտելիքների բազա",
      tasks: "Առաջադրանքների կառավարիչ",
      admin: "Ադմինիստրատորի վահանակ",
      login: "Մուտք",
      logout: "Ելք"
    },
    objects: {
      title: "Անշարժ գույքի օբյեկտներ",
      filters: "Զտիչներ",
      propertyType: "Անշարժ գույքի տեսակ",
      apartments: "Բնակարաններ",
      houses: "Տներ հողամասերով",
      commercial: "Առևտրական",
      land: "Հողամասեր",
      nonCapital: "Ոչ կապիտալ",
      shares: "Մասնաբաժիններ",
      price: "Գին",
      priceFrom: "Սկսած",
      priceTo: "Մինչև",
      area: "Տարածք (մ²)",
      areaFrom: "Սկսած",
      areaTo: "Մինչև",
      district: "Շրջան",
      allDistricts: "Բոլոր շրջանները",
      central: "Կենտրոնական",
      northern: "Հյուսիսային",
      southern: "Հարավային",
      eastern: "Արևելյան",
      western: "Արևմտյան",
      applyFilters: "Կիրառել զտիչներ",
      reset: "Վերակայել",
      found: "Գտնված",
      objects: "օբյեկտներ",
      sortBy: "Ավելացման ամսաթվով",
      sortByPriceAsc: "Գնով (աճող)",
      sortByPriceDesc: "Գնով (նվազող)",
      sortByArea: "Տարածքով",
      photo: "Նկար",
      previous: "Նախորդ",
      next: "Հաջորդ"
    },
    map: {
      title: "Ինտերակտիվ քարտեզ",
      description: "Ուսումնասիրեք անշարժ գույքի օբյեկտները քաղաքի քարտեզի վրա",
      searchPlaceholder: "Որոնում հասցեով...",
      filters: "Զտիչներ",
      showAllObjects: "Ցույց տալ բոլոր օբյեկտները",
      hideObjects: "Թաքցնել օբյեկտները",
      zoomIn: "Մեծացնել",
      zoomOut: "Փոքրացնել",
      fullscreen: "Ամբողջ էկրան",
      legend: "Բացատրություն",
      apartments: "Բնակարաններ",
      houses: "Տներ",
      commercial: "Առևտրական",
      land: "Հողամասեր"
    },
    about: {
      title: "Մեր մասին",
      description: "ՄԵՏՐԻԿԱ - առաջատար անշարժ գույքի գործակալություն",
      mission: "Մեր առաքելությունը",
      missionText: "Տրամադրել որակյալ ծառայություններ անշարժ գույքի ոլորտում",
      values: "Մեր արժեքները",
      valuesList: [
        "Մասնագիտականություն",
        "Անկեղծություն",
        "Հուսալիություն",
        "Անհատական մոտեցում"
      ],
      team: "Մեր թիմը",
      teamText: "Փորձառու մասնագետներ բազմամյա փորձով",
      experience: "Աշխատանքային փորձ",
      experienceText: "Ավելի քան 10 տարի անշարժ գույքի շուկայում"
    },
    contacts: {
      title: "Կապ",
      description: "Կապվեք մեզ հետ ցանկացած հարմար եղանակով",
      phone: "Հեռախոս",
      email: "Էլ. փոստ",
      address: "Հասցե",
      workingHours: "Աշխատանքային ժամեր",
      workingHoursText: "Երկ-Ուրբ: 9:00-18:00, Շաբ-Կիր: 10:00-16:00",
      office: "Գրասենյակ",
      officeAddress: "Մոսկվա, Տվերսկայա փողոց, 15",
      support: "Տեխնիկական աջակցություն",
      supportEmail: "support@metrika.ru"
    }
  },
  az: {
    header: {
      title: "METRİKA",
      subtitle: "Əmlak Agentliyi"
    },
    home: {
      welcome: "METRİKA əmlak agentliyinin portalına xoş gəlmisiniz. Burada əmlakla işləmək üçün lazım olan hər şeyi tapacaqsınız.",
      realEstateObjects: "Əmlak obyektləri",
      realEstateObjectsDesc: "Əmlak obyektlərini görün və idarə edin",
      interactiveMap: "İnteraktiv xəritə",
      interactiveMapDesc: "Şəhər xəritəsində obyektləri araşdırın",
      knowledgeBase: "Bilik bazası",
      knowledgeBaseDesc: "Ekspert məlumatlarına çıxış əldə edin",
      useMenu: "Portalda naviqasiya üçün sol menyudan istifadə edin"
    },
    menu: {
      home: "Ana səhifə",
      objects: "Obyektlər",
      map: "Xəritə",
      about: "Haqqımızda",
      contacts: "Əlaqə",
      blog: "Bloq",
      profile: "Profil",
      myObjects: "Mənim obyektlərim",
      academy: "Akademiya",
      knowledgeBase: "Bilik bazası",
      tasks: "Tapşırıqlar meneceri",
      admin: "Admin paneli",
      login: "Daxil ol",
      logout: "Çıxış"
    },
    objects: {
      title: "Əmlak obyektləri",
      filters: "Filtrlər",
      propertyType: "Əmlak növü",
      apartments: "Mənzillər",
      houses: "Torpaq sahəsi olan evlər",
      commercial: "Kommersiya",
      land: "Torpaq sahələri",
      nonCapital: "Qeyri-kapital",
      shares: "Paylar",
      price: "Qiymət",
      priceFrom: "Başlayaraq",
      priceTo: "Qədər",
      area: "Sahə (m²)",
      areaFrom: "Başlayaraq",
      areaTo: "Qədər",
      district: "Rayon",
      allDistricts: "Bütün rayonlar",
      central: "Mərkəzi",
      northern: "Şimali",
      southern: "Cənubi",
      eastern: "Şərqi",
      western: "Qərbi",
      applyFilters: "Filtrləri tətbiq et",
      reset: "Sıfırla",
      found: "Tapıldı",
      objects: "obyekt",
      sortBy: "Əlavə tarixinə görə",
      sortByPriceAsc: "Qiymətə görə (artan)",
      sortByPriceDesc: "Qiymətə görə (azalan)",
      sortByArea: "Sahəyə görə",
      photo: "Şəkil",
      previous: "Əvvəlki",
      next: "Növbəti"
    },
    map: {
      title: "İnteraktiv xəritə",
      description: "Şəhər xəritəsində əmlak obyektlərini araşdırın",
      searchPlaceholder: "Ünvanla axtarış...",
      filters: "Filtrlər",
      showAllObjects: "Bütün obyektləri göstər",
      hideObjects: "Obyektləri gizlə",
      zoomIn: "Böyüt",
      zoomOut: "Kiçilt",
      fullscreen: "Tam ekran",
      legend: "Açıqlama",
      apartments: "Mənzillər",
      houses: "Evlər",
      commercial: "Kommersiya",
      land: "Torpaq sahələri"
    },
    about: {
      title: "Haqqımızda",
      description: "METRİKA - aparıcı əmlak agentliyi",
      mission: "Missiyamız",
      missionText: "Əmlak sahəsində keyfiyyətli xidmətlər təqdim etmək",
      values: "Dəyərlərimiz",
      valuesList: [
        "Peşəkarlıq",
        "Dürüstlük",
        "Etibarlılıq",
        "Fərdi yanaşma"
      ],
      team: "Komandamız",
      teamText: "Çoxillik təcrübəsi olan təcrübəli mütəxəssislər",
      experience: "İş təcrübəsi",
      experienceText: "Əmlak bazarında 10 ildən çox"
    },
    contacts: {
      title: "Əlaqə",
      description: "Bizə istənilən rahat üsulla müraciət edin",
      phone: "Telefon",
      email: "E-poçt",
      address: "Ünvan",
      workingHours: "İş saatları",
      workingHoursText: "B.E: 9:00-18:00, Ş.B: 10:00-16:00",
      office: "Ofis",
      officeAddress: "Moskva, Tverskaya küçəsi, 15",
      support: "Texniki dəstək",
      supportEmail: "support@metrika.ru"
    }
  },
  zh: {
    header: {
      title: "METRIKA",
      subtitle: "房地产代理"
    },
    home: {
      welcome: "欢迎来到METRIKA房地产代理门户。在这里您将找到房地产工作所需的一切。",
      realEstateObjects: "房地产对象",
      realEstateObjectsDesc: "查看和管理房地产对象",
      interactiveMap: "交互式地图",
      interactiveMapDesc: "在城市地图上探索对象",
      knowledgeBase: "知识库",
      knowledgeBaseDesc: "获取专家信息访问权限",
      useMenu: "使用左侧菜单导航门户"
    },
    menu: {
      home: "首页",
      objects: "对象",
      map: "地图",
      about: "关于我们",
      contacts: "联系方式",
      blog: "博客",
      profile: "个人资料",
      myObjects: "我的对象",
      academy: "学院",
      knowledgeBase: "知识库",
      tasks: "任务管理器",
      admin: "管理面板",
      login: "登录",
      logout: "退出"
    },
    objects: {
      title: "房地产对象",
      filters: "过滤器",
      propertyType: "房产类型",
      apartments: "公寓",
      houses: "带土地的房屋",
      commercial: "商业",
      land: "土地",
      nonCapital: "非资本",
      shares: "股份",
      price: "价格",
      priceFrom: "从",
      priceTo: "到",
      area: "面积 (m²)",
      areaFrom: "从",
      areaTo: "到",
      district: "区域",
      allDistricts: "所有区域",
      central: "中心",
      northern: "北部",
      southern: "南部",
      eastern: "东部",
      western: "西部",
      applyFilters: "应用过滤器",
      reset: "重置",
      found: "找到",
      objects: "对象",
      sortBy: "按添加日期",
      sortByPriceAsc: "按价格（升序）",
      sortByPriceDesc: "按价格（降序）",
      sortByArea: "按面积",
      photo: "照片",
      previous: "上一页",
      next: "下一页"
    },
    map: {
      title: "交互式地图",
      description: "在城市地图上探索房地产对象",
      searchPlaceholder: "按地址搜索...",
      filters: "过滤器",
      showAllObjects: "显示所有对象",
      hideObjects: "隐藏对象",
      zoomIn: "放大",
      zoomOut: "缩小",
      fullscreen: "全屏",
      legend: "图例",
      apartments: "公寓",
      houses: "房屋",
      commercial: "商业",
      land: "土地"
    },
    about: {
      title: "关于我们",
      description: "METRIKA - 领先的房地产代理",
      mission: "我们的使命",
      missionText: "在房地产领域提供优质服务",
      values: "我们的价值观",
      valuesList: [
        "专业性",
        "诚实",
        "可靠性",
        "个性化方法"
      ],
      team: "我们的团队",
      teamText: "经验丰富的专家，多年经验",
      experience: "工作经验",
      experienceText: "在房地产市场超过10年"
    },
    contacts: {
      title: "联系方式",
      description: "以任何方便的方式联系我们",
      phone: "电话",
      email: "电子邮件",
      address: "地址",
      workingHours: "工作时间",
      workingHoursText: "周一至周五: 9:00-18:00, 周六至周日: 10:00-16:00",
      office: "办公室",
      officeAddress: "莫斯科，特维尔大街，15号",
      support: "技术支持",
      supportEmail: "support@metrika.ru"
    }
  },
  ko: {
    header: {
      title: "METRIKA",
      subtitle: "부동산 대행사"
    },
    home: {
      welcome: "METRIKA 부동산 대행사 포털에 오신 것을 환영합니다. 여기에서 부동산 작업에 필요한 모든 것을 찾을 수 있습니다.",
      realEstateObjects: "부동산 객체",
      realEstateObjectsDesc: "부동산 객체 보기 및 관리",
      interactiveMap: "대화형 지도",
      interactiveMapDesc: "도시 지도에서 객체 탐색",
      knowledgeBase: "지식 베이스",
      knowledgeBaseDesc: "전문가 정보에 대한 액세스",
      useMenu: "왼쪽 메뉴를 사용하여 포털 탐색"
    },
    menu: {
      home: "홈",
      objects: "객체",
      map: "지도",
      about: "회사 소개",
      contacts: "연락처",
      blog: "블로그",
      profile: "프로필",
      myObjects: "내 객체",
      academy: "아카데미",
      knowledgeBase: "지식 베이스",
      tasks: "작업 관리자",
      admin: "관리자 패널",
      login: "로그인",
      logout: "로그아웃"
    },
    objects: {
      title: "부동산 객체",
      filters: "필터",
      propertyType: "부동산 유형",
      apartments: "아파트",
      houses: "토지가 있는 주택",
      commercial: "상업용",
      land: "토지",
      nonCapital: "비자본",
      shares: "주식",
      price: "가격",
      priceFrom: "부터",
      priceTo: "까지",
      area: "면적 (m²)",
      areaFrom: "부터",
      areaTo: "까지",
      district: "지역",
      allDistricts: "모든 지역",
      central: "중앙",
      northern: "북부",
      southern: "남부",
      eastern: "동부",
      western: "서부",
      applyFilters: "필터 적용",
      reset: "재설정",
      found: "발견됨",
      objects: "객체",
      sortBy: "추가 날짜별",
      sortByPriceAsc: "가격별 (오름차순)",
      sortByPriceDesc: "가격별 (내림차순)",
      sortByArea: "면적별",
      photo: "사진",
      previous: "이전",
      next: "다음"
    },
    map: {
      title: "대화형 지도",
      description: "도시 지도에서 부동산 객체 탐색",
      searchPlaceholder: "주소로 검색...",
      filters: "필터",
      showAllObjects: "모든 객체 표시",
      hideObjects: "객체 숨기기",
      zoomIn: "확대",
      zoomOut: "축소",
      fullscreen: "전체 화면",
      legend: "범례",
      apartments: "아파트",
      houses: "주택",
      commercial: "상업용",
      land: "토지"
    },
    about: {
      title: "회사 소개",
      description: "METRIKA - 선도적인 부동산 대행사",
      mission: "우리의 미션",
      missionText: "부동산 분야에서 품질 서비스 제공",
      values: "우리의 가치",
      valuesList: [
        "전문성",
        "정직성",
        "신뢰성",
        "개별 접근법"
      ],
      team: "우리 팀",
      teamText: "다년간 경험을 가진 숙련된 전문가",
      experience: "작업 경험",
      experienceText: "부동산 시장에서 10년 이상"
    },
    contacts: {
      title: "연락처",
      description: "편리한 방법으로 저희에게 연락하세요",
      phone: "전화",
      email: "이메일",
      address: "주소",
      workingHours: "근무 시간",
      workingHoursText: "월-금: 9:00-18:00, 토-일: 10:00-16:00",
      office: "사무실",
      officeAddress: "모스크바, 트베르스카야 거리, 15번",
      support: "기술 지원",
      supportEmail: "support@metrika.ru"
    }
  },
  ja: {
    header: {
      title: "METRIKA",
      subtitle: "不動産代理店"
    },
    home: {
      welcome: "METRIKA不動産代理店ポータルへようこそ。ここで不動産作業に必要なすべてを見つけることができます。",
      realEstateObjects: "不動産オブジェクト",
      realEstateObjectsDesc: "不動産オブジェクトの表示と管理",
      interactiveMap: "インタラクティブマップ",
      interactiveMapDesc: "都市地図でオブジェクトを探索",
      knowledgeBase: "ナレッジベース",
      knowledgeBaseDesc: "専門家情報へのアクセス",
      useMenu: "左側のメニューを使用してポータルをナビゲート"
    },
    menu: {
      home: "ホーム",
      objects: "オブジェクト",
      map: "マップ",
      about: "会社概要",
      contacts: "連絡先",
      blog: "ブログ",
      profile: "プロフィール",
      myObjects: "マイオブジェクト",
      academy: "アカデミー",
      knowledgeBase: "ナレッジベース",
      tasks: "タスクマネージャー",
      admin: "管理者パネル",
      login: "ログイン",
      logout: "ログアウト"
    },
    objects: {
      title: "不動産オブジェクト",
      filters: "フィルター",
      propertyType: "不動産タイプ",
      apartments: "アパート",
      houses: "土地付き住宅",
      commercial: "商業用",
      land: "土地",
      nonCapital: "非資本",
      shares: "株式",
      price: "価格",
      priceFrom: "から",
      priceTo: "まで",
      area: "面積 (m²)",
      areaFrom: "から",
      areaTo: "まで",
      district: "地区",
      allDistricts: "すべての地区",
      central: "中央",
      northern: "北部",
      southern: "南部",
      eastern: "東部",
      western: "西部",
      applyFilters: "フィルターを適用",
      reset: "リセット",
      found: "見つかりました",
      objects: "オブジェクト",
      sortBy: "追加日順",
      sortByPriceAsc: "価格順（昇順）",
      sortByPriceDesc: "価格順（降順）",
      sortByArea: "面積順",
      photo: "写真",
      previous: "前へ",
      next: "次へ"
    },
    map: {
      title: "インタラクティブマップ",
      description: "都市地図で不動産オブジェクトを探索",
      searchPlaceholder: "住所で検索...",
      filters: "フィルター",
      showAllObjects: "すべてのオブジェクトを表示",
      hideObjects: "オブジェクトを非表示",
      zoomIn: "ズームイン",
      zoomOut: "ズームアウト",
      fullscreen: "フルスクリーン",
      legend: "凡例",
      apartments: "アパート",
      houses: "住宅",
      commercial: "商業用",
      land: "土地"
    },
    about: {
      title: "会社概要",
      description: "METRIKA - リーディング不動産代理店",
      mission: "私たちのミッション",
      missionText: "不動産分野で質の高いサービスを提供",
      values: "私たちの価値観",
      valuesList: [
        "プロフェッショナリズム",
        "誠実さ",
        "信頼性",
        "個別アプローチ"
      ],
      team: "私たちのチーム",
      teamText: "多年の経験を持つ熟練専門家",
      experience: "作業経験",
      experienceText: "不動産市場で10年以上"
    },
    contacts: {
      title: "連絡先",
      description: "便利な方法でお問い合わせください",
      phone: "電話",
      email: "メール",
      address: "住所",
      workingHours: "営業時間",
      workingHoursText: "月-金: 9:00-18:00, 土-日: 10:00-16:00",
      office: "オフィス",
      officeAddress: "モスクワ、トゥヴェルスカヤ通り、15番",
      support: "技術サポート",
      supportEmail: "support@metrika.ru"
    }
  },
  kk: {
    header: {
      title: "METRIKA",
      subtitle: "Жылжымайтын мүлік агенттігі"
    },
    home: {
      welcome: "METRIKA жылжымайтын мүлік агенттігі порталына қош келдіңіз. Мұнда жылжымайтын мүлікпен жұмыс істеуге қажетті барлық нәрсені табасыз.",
      realEstateObjects: "Жылжымайтын мүлік объектілері",
      realEstateObjectsDesc: "Жылжымайтын мүлік объектілерін көру және басқару",
      interactiveMap: "Интерактивті карта",
      interactiveMapDesc: "Қала картасында объектілерді зерттеу",
      knowledgeBase: "Білім базасы",
      knowledgeBaseDesc: "Сарапшы ақпаратына қол жеткізу",
      useMenu: "Порталыда навигация үшін сол мәзірді пайдаланыңыз"
    },
    menu: {
      home: "Басты бет",
      objects: "Объектілер",
      map: "Карта",
      about: "Біз туралы",
      contacts: "Байланыс",
      blog: "Блог",
      profile: "Профиль",
      myObjects: "Менің объектілерім",
      academy: "Академия",
      knowledgeBase: "Білім базасы",
      tasks: "Тапсырмалар менеджері",
      admin: "Админ панелі",
      login: "Кіру",
      logout: "Шығу"
    },
    objects: {
      title: "Жылжымайтын мүлік объектілері",
      filters: "Сүзгілер",
      propertyType: "Жылжымайтын мүлік түрі",
      apartments: "Пәтерлер",
      houses: "Жер учаскесі бар үйлер",
      commercial: "Коммерциялық",
      land: "Жер учаскелері",
      nonCapital: "Капиталды емес",
      shares: "Акциялар",
      price: "Баға",
      priceFrom: "Байланысты",
      priceTo: "Дейін",
      area: "Ауданы (м²)",
      areaFrom: "Байланысты",
      areaTo: "Дейін",
      district: "Аудан",
      allDistricts: "Барлық аудандар",
      central: "Орталық",
      northern: "Солтүстік",
      southern: "Оңтүстік",
      eastern: "Шығыс",
      western: "Батыс",
      applyFilters: "Сүзгілерді қолдану",
      reset: "Қалпына келтіру",
      found: "Табылды",
      objects: "объекті",
      sortBy: "Қосылған күні бойынша",
      sortByPriceAsc: "Баға бойынша (өсу)",
      sortByPriceDesc: "Баға бойынша (төмендеу)",
      sortByArea: "Аудан бойынша",
      photo: "Фото",
      previous: "Алдыңғы",
      next: "Келесі"
    },
    map: {
      title: "Интерактивті карта",
      description: "Қала картасында жылжымайтын мүлік объектілерін зерттеу",
      searchPlaceholder: "Мекенжай бойынша іздеу...",
      filters: "Сүзгілер",
      showAllObjects: "Барлық объектілерді көрсету",
      hideObjects: "Объектілерді жасыру",
      zoomIn: "Үлкейту",
      zoomOut: "Кішірейту",
      fullscreen: "Толық экран",
      legend: "Анықтама",
      apartments: "Пәтерлер",
      houses: "Үйлер",
      commercial: "Коммерциялық",
      land: "Жер учаскелері"
    },
    about: {
      title: "Біз туралы",
      description: "METRIKA - жылжымайтын мүлік саласындағы жетекші агенттік",
      mission: "Біздің миссиямыз",
      missionText: "Жылжымайтын мүлік саласында сапалы қызмет көрсету",
      values: "Біздің құндылықтарымыз",
      valuesList: [
        "Кәсібилік",
        "Шынайылық",
        "Сенімділік",
        "Жеке тұлғаға деген көзқарас"
      ],
      team: "Біздің командамыз",
      teamText: "Көпжылдық тәжірибесі бар тәжірибелі мамандар",
      experience: "Жұмыс тәжірибесі",
      experienceText: "Жылжымайтын мүлік нарығында 10 жылдан астам"
    },
    contacts: {
      title: "Байланыс",
      description: "Бізге ыңғайлы кез келген тәсілмен хабарласыңыз",
      phone: "Телефон",
      email: "Электрондық пошта",
      address: "Мекенжай",
      workingHours: "Жұмыс уақыты",
      workingHoursText: "Дүйсен-Жұма: 9:00-18:00, Сенбі-Жексен: 10:00-16:00",
      office: "Кеңсе",
      officeAddress: "Мәскеу, Тверская көшесі, 15-ші үй",
      support: "Техникалық қолдау",
      supportEmail: "support@metrika.ru"
    }
  },
  uz: {
    header: {
      title: "METRIKA",
      subtitle: "Ko'chmas mulk agentligi"
    },
    home: {
      welcome: "METRIKA ko'chmas mulk agentligi portaliiga xush kelibsiz. Bu yerda ko'chmas mulk bilan ishlash uchun kerakli barcha narsalarni topasiz.",
      realEstateObjects: "Ko'chmas mulk ob'ektlari",
      realEstateObjectsDesc: "Ko'chmas mulk ob'ektlarini ko'rish va boshqarish",
      interactiveMap: "Interaktiv xarita",
      interactiveMapDesc: "Shahar xaritasida ob'ektlarni o'rganish",
      knowledgeBase: "Bilim bazasi",
      knowledgeBaseDesc: "Ekspert ma'lumotlariga kirish",
      useMenu: "Portalda navigatsiya uchun chap menyudan foydalaning"
    },
    menu: {
      home: "Bosh sahifa",
      objects: "Ob'ektlar",
      map: "Xarita",
      about: "Biz haqimizda",
      contacts: "Aloqa",
      blog: "Blog",
      profile: "Profil",
      myObjects: "Mening ob'ektlarim",
      academy: "Akademiya",
      knowledgeBase: "Bilim bazasi",
      tasks: "Vazifalar menejeri",
      admin: "Admin paneli",
      login: "Kirish",
      logout: "Chiqish"
    },
    objects: {
      title: "Ko'chmas mulk ob'ektlari",
      filters: "Filtrlar",
      propertyType: "Ko'chmas mulk turi",
      apartments: "Kvartiralar",
      houses: "Er uchastkasi bilan uylar",
      commercial: "Savdo",
      land: "Er uchastkalari",
      nonCapital: "Kapital bo'lmagan",
      shares: "Aksiyalar",
      price: "Narx",
      priceFrom: "Dan",
      priceTo: "Gacha",
      area: "Maydon (m²)",
      areaFrom: "Dan",
      areaTo: "Gacha",
      district: "Tuman",
      allDistricts: "Barcha tumanlar",
      central: "Markaziy",
      northern: "Shimoliy",
      southern: "Janubiy",
      eastern: "Sharqiy",
      western: "G'arbiy",
      applyFilters: "Filtrlarni qo'llash",
      reset: "Qayta o'rnatish",
      found: "Topildi",
      objects: "ob'ekt",
      sortBy: "Qo'shilgan sana bo'yicha",
      sortByPriceAsc: "Narx bo'yicha (o'sish)",
      sortByPriceDesc: "Narx bo'yicha (pasayish)",
      sortByArea: "Maydon bo'yicha",
      photo: "Rasm",
      previous: "Oldingi",
      next: "Keyingi"
    },
    map: {
      title: "Interaktiv xarita",
      description: "Shahar xaritasida ko'chmas mulk ob'ektlarini o'rganish",
      searchPlaceholder: "Manzil bo'yicha qidirish...",
      filters: "Filtrlar",
      showAllObjects: "Barcha ob'ektlarni ko'rsatish",
      hideObjects: "Ob'ektlarni yashirish",
      zoomIn: "Kattalashtirish",
      zoomOut: "Kichiklashtirish",
      fullscreen: "To'liq ekran",
      legend: "Tushuntirish",
      apartments: "Kvartiralar",
      houses: "Uylar",
      commercial: "Savdo",
      land: "Er uchastkalari"
    },
    about: {
      title: "Biz haqimizda",
      description: "METRIKA - ko'chmas mulk sohasidagi yetakchi agentlik",
      mission: "Bizning missiyamiz",
      missionText: "Ko'chmas mulk sohasida sifatli xizmatlar ko'rsatish",
      values: "Bizning qadriyatlarimiz",
      valuesList: [
        "Professionalizm",
        "Halollik",
        "Ishonchlilik",
        "Individual yondashuv"
      ],
      team: "Bizning jamoamiz",
      teamText: "Ko'p yillik tajribaga ega tajribali mutaxassislar",
      experience: "Ish tajribasi",
      experienceText: "Ko'chmas mulk bozorida 10 yildan ortiq"
    },
    contacts: {
      title: "Aloqa",
      description: "Bizga qulay bo'lgan har qanday usul bilan bog'laning",
      phone: "Telefon",
      email: "Elektron pochta",
      address: "Manzil",
      workingHours: "Ish vaqti",
      workingHoursText: "Dush-Yak: 9:00-18:00, Shan-Yak: 10:00-16:00",
      office: "Ofis",
      officeAddress: "Moskva, Tverskaya ko'chasi, 15-uy",
      support: "Texnik yordam",
      supportEmail: "support@metrika.ru"
    }
  },
  tg: {
    header: {
      title: "METRIKA",
      subtitle: "Агентии амлок"
    },
    home: {
      welcome: "Ба METRIKA агентии амлок портал хуш омадед. Дар ин ҷо ҳама чизеро, ки барои кор бо амлок лозим аст, меёбед.",
      realEstateObjects: "Объектҳои амлок",
      realEstateObjectsDesc: "Дидани ва идора кардани объектҳои амлок",
      interactiveMap: "Харитаи интерактивӣ",
      interactiveMapDesc: "Омӯхтани объектҳо дар харитаи шаҳр",
      knowledgeBase: "Пойгоҳи дониш",
      knowledgeBaseDesc: "Дастрасӣ ба маълумоти мутахассис",
      useMenu: "Барои навигатсия дар портал аз менюи чап истифода баред"
    },
    menu: {
      home: "Саҳифаи асосӣ",
      objects: "Объектҳо",
      map: "Харита",
      about: "Дар бораи мо",
      contacts: "Тамос",
      blog: "Блог",
      profile: "Профил",
      myObjects: "Объектҳои ман",
      academy: "Академия",
      knowledgeBase: "Пойгоҳи дониш",
      tasks: "Менеҷери вазифаҳо",
      admin: "Панели админ",
      login: "Ворид шудан",
      logout: "Баромадан"
    },
    objects: {
      title: "Объектҳои амлок",
      filters: "Филтрҳо",
      propertyType: "Навъи амлок",
      apartments: "Хонаҳо",
      houses: "Хонаҳо бо замин",
      commercial: "Тиҷоратӣ",
      land: "Қитъаҳои замин",
      nonCapital: "Капиталӣ нест",
      shares: "Саҳмияҳо",
      price: "Нарх",
      priceFrom: "Аз",
      priceTo: "То",
      area: "Масоҳат (м²)",
      areaFrom: "Аз",
      areaTo: "То",
      district: "Ноҳия",
      allDistricts: "Ҳамаи ноҳияҳо",
      central: "Марказӣ",
      northern: "Шимолӣ",
      southern: "Ҷанубӣ",
      eastern: "Шарқӣ",
      western: "Ғарбӣ",
      applyFilters: "Татбиқи филтрҳо",
      reset: "Бозсозӣ",
      found: "Ёфт шуд",
      objects: "объект",
      sortBy: "Тартиби илова кардани сана",
      sortByPriceAsc: "Тартиби нарх (афзоиш)",
      sortByPriceDesc: "Тартиби нарх (камшавӣ)",
      sortByArea: "Тартиби масоҳат",
      photo: "Акс",
      previous: "Қаблӣ",
      next: "Оянда"
    },
    map: {
      title: "Харитаи интерактивӣ",
      description: "Омӯхтани объектҳои амлок дар харитаи шаҳр",
      searchPlaceholder: "Ҷустуҷӯ бо суроға...",
      filters: "Филтрҳо",
      showAllObjects: "Нишон додани ҳамаи объектҳо",
      hideObjects: "Пинҳон кардани объектҳо",
      zoomIn: "Калон кардан",
      zoomOut: "Хурд кардан",
      fullscreen: "Экрани пурра",
      legend: "Тавзеҳот",
      apartments: "Хонаҳо",
      houses: "Хонаҳо",
      commercial: "Тиҷоратӣ",
      land: "Қитъаҳои замин"
    },
    about: {
      title: "Дар бораи мо",
      description: "METRIKA - агентии пешрафтаи амлок",
      mission: "Миссияи мо",
      missionText: "Таъмин кардани хизматҳои сифатӣ дар соҳаи амлок",
      values: "Арзишҳои мо",
      valuesList: [
        "Касбият",
        "Ростӣ",
        "Эътимод",
        "Равияи шахсӣ"
      ],
      team: "Дастаи мо",
      teamText: "Мутахассисони таҷрибадор бо таҷрибаи солҳои зиёд",
      experience: "Таҷрибаи кор",
      experienceText: "Зиёда аз 10 сол дар бозори амлок"
    },
    contacts: {
      title: "Тамос",
      description: "Бо мо бо ҳар гуна роҳи қулай тамос гиред",
      phone: "Телефон",
      email: "Почтаи электронӣ",
      address: "Суроға",
      workingHours: "Вақти кор",
      workingHoursText: "Душанбе-Ҷумъа: 9:00-18:00, Шанбе-Якшанбе: 10:00-16:00",
      office: "Офис",
      officeAddress: "Москва, кӯчаи Тверская, 15",
      support: "Дастгирии техникӣ",
      supportEmail: "support@metrika.ru"
    }
  },
  hi: {
    header: {
      title: "METRIKA",
      subtitle: "रियल एस्टेट एजेंसी"
    },
    home: {
      welcome: "METRIKA रियल एस्टेट एजेंसी पोर्टल में आपका स्वागत है। यहाँ आपको रियल एस्टेट के साथ काम करने के लिए आवश्यक सब कुछ मिलेगा।",
      realEstateObjects: "रियल एस्टेट ऑब्जेक्ट्स",
      realEstateObjectsDesc: "रियल एस्टेट ऑब्जेक्ट्स देखें और प्रबंधित करें",
      interactiveMap: "इंटरैक्टिव मैप",
      interactiveMapDesc: "शहर के नक्शे पर ऑब्जेक्ट्स का अन्वेषण करें",
      knowledgeBase: "ज्ञान आधार",
      knowledgeBaseDesc: "विशेषज्ञ जानकारी तक पहुंच प्राप्त करें",
      useMenu: "पोर्टल में नेविगेट करने के लिए बाएं मेनू का उपयोग करें"
    },
    menu: {
      home: "होम",
      objects: "ऑब्जेक्ट्स",
      map: "मैप",
      about: "हमारे बारे में",
      contacts: "संपर्क",
      blog: "ब्लॉग",
      profile: "प्रोफाइल",
      myObjects: "मेरे ऑब्जेक्ट्स",
      academy: "अकादमी",
      knowledgeBase: "ज्ञान आधार",
      tasks: "टास्क मैनेजर",
      admin: "एडमिन पैनल",
      login: "लॉगिन",
      logout: "लॉगआउट"
    },
    objects: {
      title: "रियल एस्टेट ऑब्जेक्ट्स",
      filters: "फिल्टर",
      propertyType: "संपत्ति प्रकार",
      apartments: "अपार्टमेंट",
      houses: "जमीन के साथ घर",
      commercial: "व्यावसायिक",
      land: "भूमि प्लॉट",
      nonCapital: "गैर-पूंजी",
      shares: "शेयर",
      price: "मूल्य",
      priceFrom: "से",
      priceTo: "तक",
      area: "क्षेत्र (m²)",
      areaFrom: "से",
      areaTo: "तक",
      district: "जिला",
      allDistricts: "सभी जिले",
      central: "केंद्रीय",
      northern: "उत्तरी",
      southern: "दक्षिणी",
      eastern: "पूर्वी",
      western: "पश्चिमी",
      applyFilters: "फिल्टर लागू करें",
      reset: "रीसेट",
      found: "मिला",
      objects: "ऑब्जेक्ट्स",
      sortBy: "तिथि जोड़ने के अनुसार",
      sortByPriceAsc: "मूल्य के अनुसार (आरोही)",
      sortByPriceDesc: "मूल्य के अनुसार (अवरोही)",
      sortByArea: "क्षेत्र के अनुसार",
      photo: "फोटो",
      previous: "पिछला",
      next: "अगला"
    },
    map: {
      title: "इंटरैक्टिव मैप",
      description: "शहर के नक्शे पर रियल एस्टेट ऑब्जेक्ट्स का अन्वेषण करें",
      searchPlaceholder: "पते से खोजें...",
      filters: "फिल्टर",
      showAllObjects: "सभी ऑब्जेक्ट्स दिखाएं",
      hideObjects: "ऑब्जेक्ट्स छुपाएं",
      zoomIn: "ज़ूम इन",
      zoomOut: "ज़ूम आउट",
      fullscreen: "फुलस्क्रीन",
      legend: "किंवदंती",
      apartments: "अपार्टमेंट",
      houses: "घर",
      commercial: "व्यावसायिक",
      land: "भूमि प्लॉट"
    },
    about: {
      title: "हमारे बारे में",
      description: "METRIKA - अग्रणी रियल एस्टेट एजेंसी",
      mission: "हमारा मिशन",
      missionText: "रियल एस्टेट क्षेत्र में गुणवत्तापूर्ण सेवाएं प्रदान करना",
      values: "हमारे मूल्य",
      valuesList: [
        "व्यावसायिकता",
        "ईमानदारी",
        "विश्वसनीयता",
        "व्यक्तिगत दृष्टिकोण"
      ],
      team: "हमारी टीम",
      teamText: "कई वर्षों के अनुभव के साथ अनुभवी विशेषज्ञ",
      experience: "कार्य अनुभव",
      experienceText: "रियल एस्टेट बाजार में 10 से अधिक वर्ष"
    },
    contacts: {
      title: "संपर्क",
      description: "किसी भी सुविधाजनक तरीके से हमसे संपर्क करें",
      phone: "फोन",
      email: "ईमेल",
      address: "पता",
      workingHours: "कार्य समय",
      workingHoursText: "सोम-शुक्र: 9:00-18:00, शनि-रवि: 10:00-16:00",
      office: "कार्यालय",
      officeAddress: "मॉस्को, टवरस्काया स्ट्रीट, 15",
      support: "तकनीकी सहायता",
      supportEmail: "support@metrika.ru"
    }
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState('ru')

  // Получаем перевод по ключу
  const t = (key: string): string | any => {
    const keys = key.split('.')
    let value: string | Translations | any = translations[locale]
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k]
      } else {
        return key // Возвращаем ключ если перевод не найден
      }
    }
    
    return value
  }

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
